# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: meluhapool

stages:
  - stage: 
    displayName: Build and Push image to container registry
    jobs:
    - job: 
      displayName: Login to ACR
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerContainerRegistryConnection'
            command: 'login'
    - job:
      displayName: Build image
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerContainerRegistryConnection'
            repository: 'pythonproject'
            command: 'build'
            Dockerfile: 'Dockerfile'
            tags: '$(Build.BuildNumber)'
    - job: 
      displayName: Push image to container registry
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerContainerRegistryConnection'
            repository: 'pythonproject'
            command: 'push'
            tags: '$(Build.BuildNumber)'
   